package com.heheys.ec.sqliteHelper;

public interface DataBaseConstant {

	public static final int DATABASE_VERSION = 1;

	public static final String DATABASE_NAME = "businessapp.db";

	public static final String HOME_CITY_TABLE = "home_city";

	public static final String LOGIN_INFOR_TABLE = "login_infor";
	
	public static final String BUSCARD_MANAGER_TABLE = "buscard_manager";
	// 创建城市表
	public static final String CREATE_HOME_CITY_TABLE = "CREATE TABLE IF NOT EXISTS home_city (_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,CITY_ID VARCHR(20) NOT NULL UNIQUE, NAME VARCHAR(20) NOT NULL UNIQUE,HOT INTEGER);";
	// 创建登录表
	public static final String CREATE_LOGIN_INFOR_TABLE = "CREATE TABLE IF NOT EXISTS login_infor (_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,USERID VARCHAR(20) NOT NULL, MOBILE INTEGER NOT NULL,VERIFY_STATUS INTEGER,SHOPNAME TEXT);";
	// 创建名片管理表
	public static final String CREATE_BUSCARD_MANAGER_TABLE = "CREATE TABLE IF NOT EXISTS buscard_manager (_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,  NAME VARCHAR(20) NOT NULL, POSITION VARCHAR(20) NOT NULL, COMPANY VARCHAR(50) NOT NULL,MOBILE VARCHAR(50) NOT NULL,LANDLINE VARCHAR(50) NOT NULL,WEIXING VARCHAR(50) NOT NULL, ADDRESS VARCHAR(100) NOT NULL,REMARK VARCHAR(100),  TIME VARCHAR(30) NOT NULL,ID VARCHAR(30) NOT NULL,VERIFY_STATUS VARCHAR(2) NOT NULL);";
//	// 创建管理表
//	public static final String CREATE_BUSCARD_MANAGER_TABLE = "CREATE TABLE IF NOT EXISTS buscard_manager (_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,  NAME VARCHAR(20) NOT NULL, POSITION VARCHAR(20) NOT NULL, COMPANY VARCHAR(50) NOT NULL,MOBILE VARCHAR(50) NOT NULL,LANDLINE VARCHAR(50) NOT NULL,WEIXING VARCHAR(50) NOT NULL, ADDRESS VARCHAR(100) NOT NULL,REMARK VARCHAR(100),  TIME VARCHAR(30) NOT NULL,ID VARCHAR(30) NOT NULL,VERIFY_STATUS VARCHAR(2) NOT NULL);";
	//删除城市表
	public static final String DELETE_HOME_CITY_TABLE="DROP TABLE IF EXISTS home_city;";
	//删除登录用户表
	public static final String DELETE_LOGIN_INFOR_TABLE="DROP TABLE IF EXISTS  login_infor;";
	//删除名片管理表
	public static final String DELETE_BUSCARD_MANAGER_TABLE="DROP TABLE IF EXISTS  buscard_manager;";
}